### ISSUE TITLE
PA Review: User Authentication

### ISSUE THREAD

**Issue by tfaramar** [tfaramar/strava#5]
# User Auth
​
## Functionality
​
- [x] The main button with logo should link to `/`
- [x] Has working demo login
- [x] Smooth, bug free navigation
​
### Before Login
​
- [x] The `/login` page should not display a link to `Log In`. Same for `/signup`
- [x] Going to a random route `/#/oweiniouewbrviuwebv` should redirect or display a 404 page
- [x] Errors should display for both `/signup` and `/login`.
- [x] Errors should clear when moving between `/signup` and `/login`.
- [x] Can sign up a user
- [x] Can sign in as a user
- [x] Can log out a user
- [x] Can't sign up with the same username/email
- [x] Pressing enter after filling out the session form should use the form data, not the demo user
​
### After Login
​
- [x] Should not be able to visit `/login` or `/signup`
- [x] Should be able to refresh the page and still be logged in
​
​
## Style
​
- [x] The site should look exactly like the actual site
- [x] All relevant elements should have `cursor: pointer` on hover
- [x] When errors are displayed, most elements should not move around the page (particularly input boxes)
- [ ] Remove Redux logger and all console.log()'s from production
​
## Seeds
- [x] Adequate and appropriate seeds

**Comment by tfaramar** [comment]
I still need to remove the Redux logger, so I'll handle that in the next push!

**Comment by ronilbhatia** [comment]
Really great job! All the functionality is there, just make sure to update your store file to not include logger in production using the code snippet I sent to our group. I only have a couple of minor comments on styling:

1. The signup errors are reallllly small, and too close to the header of the form. Make the text bigger and give it some more padding. The login errors look great!
![Screen Shot 2020-01-09 at 5 21 43 PM](https://user-images.githubusercontent.com/32026924/72118014-93c0e700-3304-11ea-99a3-8d36d4c51f08.png)
2. Center the text here, and add email/google icons to match Strava's site. Right now these buttons feel dry, and while small the icons and centered text would go a long way.
![Screen Shot 2020-01-09 at 5 24 01 PM](https://user-images.githubusercontent.com/32026924/72118103-f74b1480-3304-11ea-985d-46fc82890743.png)
3. Add a box shadow to your input fields similar to the one that Strava has to get the glow effect (hint you can use DevTools and steal their box-shadow :))
![Screen Shot 2020-01-09 at 5 27 02 PM](https://user-images.githubusercontent.com/32026924/72118220-48f39f00-3305-11ea-98b1-4cd9dd8015ba.png)
